# Generated by Django 5.2.11 on 2026-03-06 01:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código ISO 4217. Ej: ARS, USD.', max_length=10, unique=True, verbose_name='Código ISO')),
                ('name', models.CharField(blank=True, default='', help_text='Ej: Peso Argentino, Dólar Estadounidense.', max_length=50, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa?')),
            ],
            options={
                'verbose_name': 'Moneda Fiat',
                'verbose_name_plural': 'Monedas Fiat',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Símbolo de mercado. Ej: BTC, ETH, USDT.', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(blank=True, default='', help_text='Nombre completo. Ej: Bitcoin, Ethereum.', max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Si False, no acepta nuevas operaciones pero mantiene historial.', verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='trading_asset_code_idx'), models.Index(fields=['is_active'], name='trading_asset_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(help_text='Formato: XX-XXXXXXXX-X. Identificador fiscal único.', max_length=13, unique=True, verbose_name='CUIT')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / Razón social')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('BLOCKED', 'Bloqueado')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['cuit'], name='trading_client_cuit_idx'), models.Index(fields=['status'], name='trading_client_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=10, verbose_name='Tipo')),
                ('limit_price', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Precio límite')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('FILLED', 'Ejecutada'), ('PARTIAL', 'Parcialmente ejecutada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada en')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.asset', verbose_name='Activo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.client', verbose_name='Cliente')),
                ('fiat_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.fiatcurrency', verbose_name='Moneda fiat')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=10, verbose_name='Tipo')),
                ('unit_price', models.DecimalField(decimal_places=8, help_text='Precio de ejecución en moneda fiat al momento de la operación.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Precio unitario')),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Cantidad del activo operado.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('PENDING', 'Pendiente'), ('FAILED', 'Fallida'), ('REVERSED', 'Revertida')], default='CONFIRMED', max_length=10, verbose_name='Estado')),
                ('blockchain_hash', models.CharField(blank=True, help_text='Hash de la transacción on-chain, si aplica.', max_length=255, null=True, verbose_name='Hash blockchain')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ejecutada en')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='trading.asset', verbose_name='Activo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='trading.client', verbose_name='Cliente')),
                ('fiat_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='trading.fiatcurrency', verbose_name='Moneda fiat')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='trading.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='trad_order_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['asset', 'transaction_type'], name='trading_order_asset_type_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='trading_order_status_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['client', 'created_at'], name='trading_tx_client_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['asset', 'transaction_type'], name='trading_tx_asset_type_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='trading_tx_status_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fiat_currency', 'created_at'], name='trading_tx_fiat_ts_idx'),
        ),
    ]
