# Generated by Django 6.0.2 on 2026-02-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Símbolo de mercado. Ej: BTC, ETH, USDT, ARS, USD.', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(blank=True, default='', help_text='Nombre completo del activo. Ej: Bitcoin, Ethereum.', max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Si False, el activo no acepta nuevas operaciones pero mantiene el historial histórico intacto.', verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='brokerage_asset_code_idx'), models.Index(fields=['is_active'], name='brokerage_asset_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(help_text='Formato: XX-XXXXXXXX-X. Identificador fiscal único.', max_length=13, unique=True, verbose_name='CUIT')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / Razón social')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('BLOCKED', 'Bloqueado')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['cuit'], name='brokerage_client_cuit_idx'), models.Index(fields=['status'], name='brokerage_client_status_idx')],
            },
        ),
    ]
