"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This will be overridden in each environment
SECRET_KEY = 'django-insecure-lb_d7=8=e@2e0%)kr+90d5)2gl-z_n2v!+iunqdyrl+2xl5-7e'

# SECURITY WARNING: don't run with debug turned on in production!
# This will be overridden in each environment
DEBUG = False



ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.users',
    'apps.authorization',
    'apps.audit',
    'apps.brokerage',
    'apps.playground',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # No puede ser demasiado similar al email, nombre o apellido
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {'max_similarity': 0.7},
    },
    {
        # Mínimo 10 caracteres
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        # No puede ser una contraseña de uso común (lista de 20.000)
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # No puede ser completamente numérica
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # Al menos: 1 mayúscula, 1 minúscula, 1 número y 1 carácter especial
        'NAME': 'apps.users.validators.PasswordComplexityValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'KaizenUTN API',
    'DESCRIPTION': (
        'API REST del sistema KaizenUTN. Autenticación JWT, control de acceso por roles (RBAC) y auditoría de eventos.\n\n'
        '---\n\n'
        '## Cómo autenticarse\n\n'
        '1. Ejecutar `POST /api/auth/login/` con email y contraseña.\n'
        '2. Copiar el valor del campo `access` de la respuesta.\n'
        '3. Hacer click en **Authorize 🔒** (arriba a la derecha) e ingresar `Bearer <access_token>`.\n'
        '4. Todos los endpoints con el candado usarán ese token automáticamente.\n\n'
        '> El token `access` expira en **60 minutos**. Renovarlo con `POST /api/auth/refresh/`.\n'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {
            'name': 'Autenticación',
            'description': 'Registro, login, logout y renovación de tokens JWT.',
        },
        {
            'name': 'Perfil',
            'description': 'Ver y editar el perfil del usuario autenticado. Cambio de contraseña.',
        },
        {
            'name': 'Usuarios',
            'description': (
                'Gestión administrativa de cuentas: listar, crear, editar, desactivar y resetear contraseña.\n\n'
                '| Permiso requerido | Operación |\n'
                '|-------------------|-----------|\n'
                '| `usuarios.view` | Listar / Ver |\n'
                '| `usuarios.create` | Crear |\n'
                '| `usuarios.edit` | Editar / Reset contraseña |\n'
                '| `usuarios.delete` | Desactivar |'
            ),
        },
        {
            'name': 'Auditoría',
            'description': (
                'Consulta del historial inmutable de eventos del sistema.\n\n'
                'Requiere permiso `auditoria.view` (rol Administrador).'
            ),
        },
    ],
    'PREPROCESSING_HOOKS': [
        'config.spectacular_hooks.exclude_playground',
    ],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 1,
        'defaultModelExpandDepth': 2,
        'docExpansion': 'none',
        'filter': True,
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'SECURITY': [{'bearerAuth': []}],
    'SECURITY_DEFINITIONS': {
        'bearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': (
                'Token JWT obtenido desde `POST /api/auth/login/` o `POST /api/auth/register/`.\n\n'
                'Formato: `Bearer <access_token>`'
            ),
        }
    },
}

#jwt settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
}

# Password Hashing - Argon2 (más seguro)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'users.User'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'