"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This will be overridden in each environment
SECRET_KEY = 'django-insecure-lb_d7=8=e@2e0%)kr+90d5)2gl-z_n2v!+iunqdyrl+2xl5-7e'

# SECURITY WARNING: don't run with debug turned on in production!
# This will be overridden in each environment
DEBUG = False



ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.users',
    'apps.authorization',
    'apps.audit',
    'apps.playground',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'KaizenUTN API',
    'DESCRIPTION': (
        'REST API para el sistema KaizenUTN.\n\n'

        '---\n\n'

        '## 🔐 Módulo Identity — Autenticación JWT\n\n'
        'Gestiona el ciclo de vida de sesiones mediante **JSON Web Tokens (JWT)** '
        'con la librería `djangorestframework-simplejwt`.\n\n'
        '### Flujo de autenticación\n'
        '1. **Registrarse** → `POST /api/auth/register/` — crea cuenta y retorna tokens.\n'
        '2. **Iniciar sesión** → `POST /api/auth/login/` — retorna `access` + `refresh` token.\n'
        '3. **Usar la API** → incluir `Authorization: Bearer <access_token>` en cada request protegido.\n'
        '4. **Renovar token** → `POST /api/auth/refresh/` cuando el `access` expire (60 min).\n'
        '5. **Cerrar sesión** → `POST /api/auth/logout/` invalida el `refresh` token (blacklist).\n\n'
        '### Endpoints de Identity\n'
        '| Endpoint | Método | Auth | Descripción |\n'
        '|----------|--------|------|-------------|\n'
        '| `/api/auth/register/` | POST | ❌ | Registro de nuevo usuario |\n'
        '| `/api/auth/login/` | POST | ❌ | Inicio de sesión |\n'
        '| `/api/auth/logout/` | POST | ✅ | Cierre de sesión (blacklist refresh token) |\n'
        '| `/api/auth/refresh/` | POST | ❌ | Renovar access token con refresh token |\n'
        '| `/api/auth/profile/` | GET/PUT/PATCH | ✅ | Ver y editar perfil propio |\n'
        '| `/api/auth/change-password/` | POST | ✅ | Cambiar contraseña |\n\n'

        '---\n\n'

        '## 🛡️ Módulo Authorization — RBAC (Role-Based Access Control)\n\n'
        'Sistema de autorización desacoplado del módulo Identity. Determina **qué puede hacer** '
        'cada usuario, independientemente de cómo se autenticó.\n\n'
        '### Arquitectura\n'
        '```\n'
        'Usuario  ──FK──►  Rol  ──M2M──►  Permiso\n'
        '                  (name)          (code, description)\n'
        '```\n\n'
        '- Un usuario tiene **un rol** (ForeignKey, on_delete=PROTECT).\n'
        '- Un rol puede tener **N permisos** (ManyToMany).\n'
        '- Los códigos de permiso siguen la convención `<dominio>.<acción>`, ej: `conciliacion.run`.\n\n'
        '### Roles del sistema\n'
        '| Rol | Permisos incluidos |\n'
        '|-----|--------------------|\n'
        '| **Operador** | `conciliacion.view`, `reportes.view`, `dashboard.view` — asignado automáticamente al registrarse |\n'
        '| **Administrador** | Todos los permisos del sistema (11 permisos) |\n\n'
        '### Clases de permiso DRF disponibles\n'
        '| Clase | Lógica | Ejemplo de uso |\n'
        '|-------|--------|----------------|\n'
        '| `HasPermission("x")` | Requiere el permiso `x` | Operaciones con permiso único |\n'
        '| `HasAnyPermission("x", "y")` | Requiere `x` **OR** `y` | Recursos compartidos entre roles |\n'
        '| `HasAllPermissions("x", "y")` | Requiere `x` **AND** `y` | Operaciones críticas, máxima granularidad |\n\n'
        '### Propiedad clave — Cambio de rol en tiempo real\n'
        'El módulo **consulta la base de datos en cada request** (`user.role.permissions.filter(code=...).exists()`). '
        'Cambiar el rol de un usuario en el panel admin surte efecto en el siguiente request '
        'sin necesidad de revocar ni renovar tokens JWT.\n\n'
        '### Endpoints de Authorization\n'
        '| Endpoint | Método | Permiso requerido | Clase usada |\n'
        '|----------|--------|-------------------|-------------|\n'
        '| `/api/authorization/me/permissions/` | GET | Solo autenticado | — |\n'
        '| `/api/authorization/conciliacion/run/` | POST | `conciliacion.run` | `HasPermission` |\n'
        '| `/api/authorization/conciliacion/` | GET | `conciliacion.view` | `HasPermission` |\n'
        '| `/api/authorization/dashboard/` | GET | `dashboard.view` OR `admin.full` | `HasAnyPermission` |\n'
        '| `/api/authorization/admin/panel/` | GET | `admin.read` AND `admin.write` | `HasAllPermissions` |\n\n'

        '---\n\n'

        '## 📋 Cómo usar el Swagger interactivo\n\n'
        '1. Ir a `POST /api/auth/login/` e ingresar credenciales.\n'
        '2. Copiar el valor del campo `access` de la respuesta.\n'
        '3. Hacer click en el botón **Authorize 🔒** (arriba a la derecha).\n'
        '4. Ingresar `Bearer <access_token>` en el campo `bearerAuth`.\n'
        '5. Ahora todos los endpoints marcados con 🔒 usarán ese token automáticamente.\n'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'docExpansion': 'list',
        'filter': True,
        'tagsSorter': 'alpha',
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'SECURITY': [{'bearerAuth': []}],
    'SECURITY_DEFINITIONS': {
        'bearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': (
                'Token JWT obtenido desde `POST /api/auth/login/` o `POST /api/auth/register/`.\n\n'
                'Formato: `Bearer <access_token>`'
            ),
        }
    },
}

#jwt settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
}

# Password Hashing - Argon2 (más seguro)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'users.User'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'