# Generated by Django 6.0.2 on 2026-02-20 22:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Identificador de la acción. Convención: "<recurso>.<verbo>" — ej: "user.created".', max_length=100, verbose_name='Acción')),
                ('resource', models.CharField(db_index=True, help_text='Tipo de recurso afectado. Ej: "user", "payment", "report".', max_length=100, verbose_name='Recurso')),
                ('resource_id', models.CharField(blank=True, default='', help_text='Identificador del recurso específico afectado (opcional).', max_length=255, verbose_name='ID del recurso')),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('FAILURE', 'Fallido')], db_index=True, default='SUCCESS', max_length=10, verbose_name='Estado')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contexto adicional en formato JSON. NUNCA incluir datos sensibles: passwords, tokens, claves privadas.', verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP de origen de la solicitud.', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Identificación del cliente HTTP.', verbose_name='User-Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora UTC de creación. Inmutable.', verbose_name='Timestamp')),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='UUID que correlaciona múltiples eventos de una misma operación. Útil para trazabilidad en arquitecturas orientadas a eventos.', verbose_name='Correlation ID')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la acción. Null para acciones anónimas o del sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'abstract': False,
                'indexes': [models.Index(fields=['action', 'resource'], name='audit_auditlog_action_resource_idx'), models.Index(fields=['status', 'timestamp'], name='audit_auditlog_status_ts_idx'), models.Index(fields=['user', 'timestamp'], name='audit_auditlog_user_ts_idx')],
            },
        ),
    ]
