# Generated by Django 6.0.2 on 2026-02-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_auditlog_act_res_idx',
            old_name='audit_auditlog_action_resource_idx',
        ),
    ]
